export const CAPABILITIES = {
  DOMAIN_PORTFOLIO_READ: "domain.portfolio.read",
  DNS_RECORD_READ: "dns.record.read",
  DNS_RECORD_WRITE: "dns.record.write",
  VPS_RESOURCE_READ: "vps.resource.read",
  VPS_RESTART: "vps.restart",
  VPS_METRICS_READ: "metrics.vps.read",
  HOSTING_WEBSITE_READ: "website.hosting.read",
  HOSTING_RUNTIME_RESTART: "hosting.runtime.restart",
  HOSTING_NEXTJS_RUNTIME: "hosting.runtime.nextjs",
  EMAIL_MAILBOX_READ: "email.mailbox.read",
  EMAIL_MAILBOX_MANAGE: "email.mailbox.manage",
  SSL_CERTIFICATE_EXPIRY_READ: "ssl.certificate.expiry.read",
  SSL_CERTIFICATE_MANAGE: "ssl.certificate.manage",
  FILE_OPERATION_MANAGE: "file.operation.manage",
  DEPLOYMENT_ARCHIVE_BUILD: "deployment.archive.build",
  DEPLOYMENT_DOCKER_COMPOSE_EXECUTE: "deployment.docker-compose.execute",
  LOGS_BUILD_READ: "logs.build.read",
  BACKUP_VPS_READ: "backup.vps.read",
  BACKUP_VPS_RESTORE: "backup.vps.restore",
  SNAPSHOT_VPS_READ: "snapshot.vps.read",
  SNAPSHOT_VPS_RESTORE: "snapshot.vps.restore",
  DATABASE_POSTGRESQL_QUERY: "database.postgresql.query",
  DATABASE_BACKUP_READ: "backup.database.read",
  AUTHENTICATION_SESSION_MANAGE: "authentication.session.manage",
  STORAGE_OBJECT_MANAGE: "storage.object.manage",
  EDGE_FUNCTION_INVOKE: "edge-function.invoke",
  EDGE_FUNCTION_MANAGE: "edge-function.manage",
  REALTIME_CHANNEL_SUBSCRIBE: "realtime.channel.subscribe",
  METRICS_PLATFORM_READ: "metrics.platform.read",
  LOGS_PLATFORM_READ: "logs.platform.read",
  REPOSITORY_READ: "repository.read",
  REPOSITORY_WRITE: "repository.write",
  RELEASE_READ: "release.read",
  RELEASE_WRITE: "release.write",
  CI_WORKFLOW_READ: "ci.workflow.read",
  CI_WORKFLOW_DISPATCH: "ci.workflow.dispatch",
  CI_RUN_READ: "ci.run.read",
  CI_RUN_CONTROL: "ci.run.control",
  LOGS_CI_READ: "logs.ci.read",
  SOURCE_COMMIT_METADATA_READ: "source.commit-metadata.read",
  SOURCE_TAG_READ: "source.tag.read",
  SOURCE_VERSION_READ: "source-version.read",
  HEALTH_SERVICE_STATUS_READ: "health.service-status.read",
  HEALTH_ENDPOINT_PROBE: "health.endpoint.probe",
} as const;

export type KnownCapabilityId = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];
