import { z } from "zod";
import type {
  Assignment,
  ContactAttempt,
  FieldVisit,
  PromiseToPay,
  RecoveryCase,
  TimelineEvent,
  VisitResult,
  WorkflowTransition,
} from "../../domain/entities";
const ts = z.string();
export const caseRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  branch_id: z.uuid(),
  customer_id: z.uuid(),
  contract_id: z.uuid().nullable(),
  status_id: z.uuid(),
  priority: z.string(),
  opened_at: ts,
  next_action_at: ts,
  closed_at: ts.nullable(),
  version_no: z.number().int(),
  business_object_id: z.uuid(),
  created_at: ts,
  updated_at: ts,
});
export const timelineRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  case_id: z.uuid(),
  event_type: z.string(),
  occurred_at: ts,
  actor_user_id: z.uuid().nullable(),
  source_type: z.string(),
  source_id: z.uuid(),
  summary: z.string(),
  payload_json: z.record(z.string(), z.unknown()),
  schema_version: z.number().int(),
  event_version_id: z.uuid(),
  correlation_id: z.uuid().or(z.string()),
  causation_id: z.uuid(),
  visibility_code: z.string(),
  created_at: ts,
});
export const assignmentRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  case_id: z.uuid(),
  agent_id: z.uuid(),
  team_id: z.uuid().nullable(),
  status_id: z.uuid(),
  assigned_at: ts,
  due_at: ts,
  completed_at: ts.nullable(),
  version_no: z.number().int(),
  business_object_id: z.uuid(),
  created_at: ts,
  updated_at: ts,
});
export const fieldVisitRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  assignment_id: z.uuid(),
  scheduled_at: ts,
  started_at: ts.nullable(),
  completed_at: ts.nullable(),
  outcome_code: z.string(),
  version_no: z.number().int(),
  business_object_id: z.uuid(),
  created_at: ts,
  updated_at: ts,
});
export const visitResultRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  visit_id: z.uuid().nullable(),
  outcome_type: z.string(),
  payload_json: z.record(z.string(), z.unknown()),
  schema_version: z.number().int(),
  created_at: ts,
});
export const contactAttemptRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  visit_id: z.uuid().nullable(),
  customer_contact_id: z.uuid(),
  channel_code: z.string(),
  outcome_code: z.string(),
  occurred_at: ts,
  actor_membership_id: z.uuid(),
  created_at: ts,
});
export const promiseRowSchema = z.object({
  id: z.uuid(),
  partner_id: z.uuid(),
  case_id: z.uuid(),
  visit_id: z.uuid().nullable(),
  customer_id: z.uuid(),
  promised_amount: z.coerce.number(),
  currency_code: z.string(),
  due_at: ts,
  status_code: z.string(),
  version_no: z.number().int(),
  created_at: ts,
  updated_at: ts,
});
export const transitionRowSchema = z.object({
  id: z.uuid(),
  from_state_id: z.uuid().nullable(),
  to_state_id: z.uuid(),
  action_code: z.string(),
  permission_code: z.string(),
});
export const toCase = (r: z.infer<typeof caseRowSchema>): RecoveryCase => ({
  id: r.id,
  partnerId: r.partner_id,
  branchId: r.branch_id,
  customerId: r.customer_id,
  contractId: r.contract_id,
  statusId: r.status_id,
  priority: r.priority,
  openedAt: r.opened_at,
  nextActionAt: r.next_action_at,
  closedAt: r.closed_at,
  versionNo: r.version_no,
  businessObjectId: r.business_object_id,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});
export const toTimeline = (r: z.infer<typeof timelineRowSchema>): TimelineEvent => ({
  id: r.id,
  partnerId: r.partner_id,
  caseId: r.case_id,
  eventType: r.event_type,
  occurredAt: r.occurred_at,
  actorUserId: r.actor_user_id,
  sourceType: r.source_type,
  sourceId: r.source_id,
  summary: r.summary,
  payloadJson: r.payload_json,
  schemaVersion: r.schema_version,
  eventVersionId: r.event_version_id,
  correlationId: r.correlation_id,
  causationId: r.causation_id,
  visibilityCode: r.visibility_code,
  createdAt: r.created_at,
});
export const toAssignment = (r: z.infer<typeof assignmentRowSchema>): Assignment => ({
  id: r.id,
  partnerId: r.partner_id,
  caseId: r.case_id,
  agentId: r.agent_id,
  teamId: r.team_id,
  statusId: r.status_id,
  assignedAt: r.assigned_at,
  dueAt: r.due_at,
  completedAt: r.completed_at,
  versionNo: r.version_no,
  businessObjectId: r.business_object_id,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});
export const toFieldVisit = (r: z.infer<typeof fieldVisitRowSchema>): FieldVisit => ({
  id: r.id,
  partnerId: r.partner_id,
  assignmentId: r.assignment_id,
  scheduledAt: r.scheduled_at,
  startedAt: r.started_at,
  completedAt: r.completed_at,
  outcomeCode: r.outcome_code,
  versionNo: r.version_no,
  businessObjectId: r.business_object_id,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});
export const toVisitResult = (r: z.infer<typeof visitResultRowSchema>): VisitResult => ({
  id: r.id,
  partnerId: r.partner_id,
  visitId: r.visit_id,
  outcomeType: r.outcome_type,
  payloadJson: r.payload_json,
  schemaVersion: r.schema_version,
  createdAt: r.created_at,
});
export const toContact = (r: z.infer<typeof contactAttemptRowSchema>): ContactAttempt => ({
  id: r.id,
  partnerId: r.partner_id,
  visitId: r.visit_id,
  customerContactId: r.customer_contact_id,
  channelCode: r.channel_code,
  outcomeCode: r.outcome_code,
  occurredAt: r.occurred_at,
  actorMembershipId: r.actor_membership_id,
  createdAt: r.created_at,
});
export const toPromise = (r: z.infer<typeof promiseRowSchema>): PromiseToPay => ({
  id: r.id,
  partnerId: r.partner_id,
  caseId: r.case_id,
  visitId: r.visit_id,
  customerId: r.customer_id,
  promisedAmount: r.promised_amount,
  currencyCode: r.currency_code,
  dueAt: r.due_at,
  statusCode: r.status_code,
  versionNo: r.version_no,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});
export const toTransition = (r: z.infer<typeof transitionRowSchema>): WorkflowTransition => ({
  id: r.id,
  fromStateId: r.from_state_id,
  toStateId: r.to_state_id,
  actionCode: r.action_code,
  permissionCode: r.permission_code,
});
